// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
// SPDX-License-Identifier: GPL-3.0-or-later

package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// LayoutData carries runtime-computed values injected into the page shell.
type LayoutData struct {
	StyleHash       string // hex hash suffix of the versioned CSS file
	DatastarVersion string // e.g. "1.0.1"
}

// Layout renders the page shell. The body opens an SSE connection to
// /ui/sse on load (data-on-load); the daemon emits one
// datastar-patch-elements event per configured device on connect, then
// streams updates from the poller. There is no client-side polling.
func Layout(d LayoutData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><title>breezy</title><script>\n\t\t\t\tvar t = localStorage.getItem(\"theme\");\n\t\t\t\tif (t === \"light\" || t === \"dark\") {\n\t\t\t\t\tdocument.documentElement.setAttribute(\"data-theme\", t);\n\t\t\t\t}\n\t\t\t</script><link rel=\"stylesheet\" href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 templ.SafeURL
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs("/ui/style-" + d.StyleHash + ".css")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/breezyd/ui/templates/layout.templ`, Line: 28, Col: 68}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"><script type=\"module\" src=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs("/ui/vendor/datastar-" + d.DatastarVersion + ".min.js")
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `cmd/breezyd/ui/templates/layout.templ`, Line: 29, Col: 85}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"></script><script src=\"/ui/vendor/dashboard.js\"></script></head><body data-on-load=\"@get('/ui/sse')\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ThemePicker().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div id=\"global-error-banner\" aria-live=\"polite\"></div><div id=\"device-list\" class=\"grid\"></div><script>\n(function() {\n  var picker = document.querySelector('.theme-picker');\n  if (!picker) return;\n  // Force closed on load: some browsers preserve <details open> across\n  // bfcache restores or session restore, which would show the popout\n  // before any user interaction.\n  picker.open = false;\n  picker.addEventListener('click', function(ev) {\n    var target = ev.target.closest('[data-theme-set]');\n    if (!target) return;\n    var theme = target.getAttribute('data-theme-set');\n    if (theme === 'auto') {\n      document.documentElement.removeAttribute('data-theme');\n      localStorage.removeItem('theme');\n    } else {\n      document.documentElement.setAttribute('data-theme', theme);\n      localStorage.setItem('theme', theme);\n    }\n    picker.open = false;\n  });\n  document.addEventListener('click', function(ev) {\n    if (picker.open && !picker.contains(ev.target)) {\n      picker.open = false;\n    }\n  });\n})();\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
